name: Pull Request Merged

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup python 3
      uses: actions/setup-python@v1
      with:
        python-version: 3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


    # configure AWS keys
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: AKIAX3XXRYO45YEQ7S5X
        aws-secret-access-key: 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
        aws-region: us-east-1
    # validate templates
    - name: Validate Template
      uses: hashicorp/packer-github-actions@master
      with:
        command: validate
        arguments: -syntax-only
        target: ./packer-ami/AmazonMachineImage.pkr.hcl

    # init packer packages
    - name: Init Template
      uses: hashicorp/packer-github-actions@master
      with:
        command: init
        target: ./packer-ami/AmazonMachineImage.pkr.hcl
    # build artifact
    - name: Build Artifact
      uses: hashicorp/packer-github-actions@master
      with:
        command: build
        arguments: "-color=false -on-error=abort "
        target: ./packer-ami/AmazonMachineImage.hcl
      env:
        PACKER_LOG: 1
        GITHUB_REPO_PATH: ${{ github.workspace }}