# This is a basic workflow to help you get started with Actions
name: PullRequestRaised

# Controls when the workflow will run
on: 
  push:
    branches: [main]
  pull_request:
    branches: [main]
jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Setup python 3
      uses: actions/setup-python@v1
      with:
        python-version: 3
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
        pip install -r requirements.txt


    # configure AWS keys
    - name: Configure AWS Credentials
      uses: aws-actions/configure-aws-credentials@v1
      with:
        aws-access-key-id: ${{ secrets.ACCESS_KEY }}
        aws-secret-access-key: ${{ secrets.SECRET_ACCESS }}
        aws-region: us-east-1
    # validate templates
    - name: Validate Template
      uses: hashicorp/packer-github-actions@master
      with:
        command: validate
        arguments: -syntax-only
        target: ./packer-ami/AmazonMachineImage.pkr.hcl

    # init packer packages
    - name: Init Template
      uses: hashicorp/packer-github-actions@master
      with:
        command: init
        target: ./packer-ami/AmazonMachineImage.pkr.hcl
